const loginFields = [
    {
        labelText:"Email address",
        labelFor:"email-address",
        id:"email",
        name:"email",
        type:"email",
        autoComplete:"email",
        isRequired:true,
        placeholder:"Email address"   
    },
    {
        labelText: 'Password',
        labelFor: 'password',
        id: 'password',
        name: 'password',
        type: 'password',
        autoComplete: 'current-password',
        isRequired: true,
        placeholder: 'Password',
    },
];

const signupFields = [
    {
        labelText: 'Firstname',
        labelFor: 'firstname',
        id: 'firstname',
        name: 'firstname',
        type: 'text',
        autoComplete: 'firstname',
        isRequired: true,
        placeholder: 'Firstname',
    },
    {
        labelText: 'Lastname',
        labelFor: 'lastname',
        id: 'lastname',
        name: 'lastname',
        type: 'text',
        autoComplete: 'lastname',
        isRequired: true,
        placeholder: 'Lastname',
    },
    {
        labelText:"Email address",
        labelFor:"email-address",
        id:"email",
        name:"email",
        type:"email",
        autoComplete:"email",
        isRequired:true,
        placeholder:"Email address"   
    },
    {
        labelText: 'Password',
        labelFor: 'password',
        id: 'password',
        name: 'password',
        type: 'password',
        autoComplete: 'current-password',
        isRequired: true,
        placeholder: 'Password',
    },
    {
        labelText: 'Confirm Password',
        labelFor: 'confirm-password',
        id: 'confirm-password',
        name: 'confirm-password',
        type: 'password',
        autoComplete: 'confirm-password',
        isRequired: true,
        placeholder: 'Confirm Password',
    },
    {
        labelText: 'Phone Number',
        labelFor: 'phonenumber',
        id: 'phonenumber',
        name: 'phonenumber',
        type: 'text',
        autoComplete: 'phonenumber',
        isRequired: true,
        placeholder: 'phonenumber',
    },
];
export { loginFields, signupFields };